### ISSUE TITLE
Add section links without the need for JavaScript

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/kuma#5718]
From some testing, it would seem that the JavaScript DOM manipulation to add section links is causing layout thrashing. Could there be a way to process the Article contents and inject these when the document is being server-side rendered?

**Comment by atopal** [comment]
I'd also be okay with removing these now that we have a table of contents again for all pages or alternatively, instrument this to see how many people are actually using it before we spend time optimizing (and we should probably instrument it either way).

**Comment by peterbe** [comment]
> Could there be a way to process the Article contents and inject these when the document is being server-side rendered?

Yes, let me attempt this. Entirely in Python. If I get it right none of the (S)CSS should be affected.

**Comment by schalkneethling** [comment]
Pull request(https://github.com/mozilla/kuma/pull/5719) started a nice discussion and the conclusion is: Do it on the back-backend

**Comment by schalkneethling** [comment]
@atopal When this is done in Python and we have no JS anymore related to this, would you still want us to add JS to instrument or should we just safely assume people like this feature?

**Comment by atopal** [comment]
We should still instrument it, but I'd rather do that before we do the work here to re-implement this feature.

**Comment by peterbe** [comment]
@atopal Can you instrument right-clicks of people selecting to "Copy link location..."? 
I'd personally hate to see section anchor links go away. They are so useful. And the way they're currently implemented, pardon my French, suck. I'm close to a resolution already that will take a good chunk out of the DOM CPU bound work that clearly is killing our performance.

**Comment by atopal** [comment]
@peterbe yeah, I think you can use onContextMenu for that. The purpose of instrumenting this was to not spend time optimizing it, in case we don't need to. Instrumenting is quick and we can get answer within a day. 

The reason we added this feature was because we had removed the TOC. Now that we have a TOC again, it's nice, but not a priority. You can right click the TOC to get the same result.

**Comment by peterbe** [comment]
@escattone Note that https://github.com/mozilla/kuma/pull/5728 doesn't automatically resolve this. We'll still have a bunch of JavaScript to inject anchor links. Both in the wiki and in the React side. The reason is that on the being anonymous on the Wiki (if you can ever be anonymous any more!) or browsing the read-only site it relies on `Document.body_html` statically. That field only gets regenerated if you edit the document. 

We *could* run a massive re-render and once we've done that, return to this issue and make another PR that deletes all those JavaScript codes that adds anchor links by mutating the DOM. Thoughts?

**Comment by peterbe** [comment]
In https://github.com/mozilla/kuma/issues/5738 we decided to abandon it entirely. If there's a big outcry for it, we can enable it later by re-opening https://github.com/mozilla/kuma/pull/5728
