### ISSUE TITLE
Get Github Avatar URL prior to MDN Acct creation

### ISSUE THREAD

**Issue by tobinmori** [mozilla/kuma#5888]
During the MDN signup flow, after the user has already signed-in to GitHub but prior to the creation of her/his MDN account:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/3743693/66528589-49d22600-eab5-11e9-9e66-23010f76f683.png">

we need to know how to get the user's GitHub avatar URL so it can be used instead of the generic `dino` image.

**Comment by escattone** [comment]
This turned out to be much easier than I anticipated, and the answer emerged from my work on #5911:

Within the `kuma/users/jinja2/socialaccount/signup.html` Jinja2 template (which is used for the signup flow), there is an `account` Python variable, which, for example, is used [here](https://github.com/mozilla/kuma/blob/f28dd92eab09dd3fbabc927b0e15da9ea8d98229/kuma/users/jinja2/socialaccount/signup.html#L17). That `account` variable is injected into the template's context by the `/<locale>/users/account/signup` view's base class in `django.allauth`, and it's the actual social account that would be created for the user if they hit the `Create profile` button. That's good news, because it already contains all of the information from GitHub, including email addresses and the user's avatar URL. So, for example, to get the user's GitHub avatar URL, you could add this to the template:
```
{% set avatar_url = account.get_avatar_url() %}
```
and then use it as the user's avatar instead of the [`mdn-profile` CSS class]
