### ISSUE TITLE
Investigate User Acct creation

### ISSUE THREAD

**Issue by tobinmori** [mozilla/kuma#5911]

**Comment by jmswisher** [comment]
Needs Acceptance Criteria

**Comment by schalkneethling** [comment]
Hey @escattone,

Here is what I think needs to be investigated:

### What do we get back from Github post auth?

### We seem to have the username that is associated with the Github account, and then also their email addresses. I assume verified for email addresses here means verified on the Github side?

### Currently, once a user clicks `Create account`, we check whether the username already exists on our side. This new flow requires us to do the username portion *before* the user has clicked on `Create account`

We probably need a flag on the Jinja side along the lines of `is_username_taken` to determine whether to use the username from Github or present the user with a text input.

On this topic, is there an API endpoint that we can call from the client-side to determine this on-demand? I am thinking that it will be useful in cases where a user is presented with the blank text input or, they choose to change the username during sign-up. 

We can then do a call to this endpoint once the username field loses focus. That way the user does not have to click "`Create account` and only then be informed that the chosen username is already taken.

### Following on from the above I believe we do the same for the chosen email address.

There is no requirement to do this before the user clicks `Create account`, though if there is an API endpoint to call, it could make for a smoother signup experience, especially if the user chooses "Other" and enters a different email to those we received from Github.

There may be additional things that come up as I implement this, but this is a good start. Thanks Ryan!

**Comment by escattone** [comment]
Thank you @schalkneethling!

**Comment by escattone** [comment]
@schalkneethling Wow, trying to understand the code behind account signup is a mind-bending experience. The functionality is so scattered among various classes, base classes, adapters, templates, and so on among `kuma.users`, `django-allauth`, and `django`. Here's what I've found so far:

- Within the `kuma/users/jinja2/socialaccount/signup.html` Jinja2 template (which is used for the signup flow), there is an `account` Python variable, which, for example, is used [here](https://github.com/mozilla/kuma/blob/f28dd92eab09dd3fbabc927b0e15da9ea8d98229/kuma/users/jinja2/socialaccount/signup.html#L17). That `account` variable is injected into the template's context by the `/<locale>/users/account/signup` view's base class in `django.allauth`, and it's the actual social account that would be created for the user if they hit the `Create profile` button. That's good news, because it already contains all of the information from GitHub, including email addresses and the user's avatar URL. So, for example, to get the user's GitHub avatar URL, you could add this to the template:
  ```
  {% set avatar_url = account.get_avatar_url() %}
  ```
  and then use it as the user's avatar instead of the [`mdn-profile` CSS class](https://github.com/mozilla/kuma/blob/f28dd92eab09dd3fbabc927b0e15da9ea8d98229/kuma/users/jinja2/socialaccount/signup.html#L70).

- You can get the email addresses in the template via:
  ```
  {% set email_addresses = account.get_email_addresses() %}
  ```
  The `email_addresses` variable above would be a list of dictionaries, where that list includes both verified and unverified email addresses from GitHub, and where each dictionary represents a single email address and has the keys `email` (the actual email address as a string), `verified` (boolean, which means verified by GitHub), `primary` (boolean), and `visibility` (a string, we should only use email addresses with a visibility of `"public"`).

- >We probably need a flag on the Jinja side along the lines of is_username_taken to determine whether to use the username from Github or present the user with a text input.

  We do an initial check when first loading the form if the username is already taken by another user and indicate that:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/3743693/66443003-504b9980-e9f2-11e9-8e34-081ada431fa2.png">
  But we don't check again if the user changes the username text input. I don't think we have nice endpoint for checking if a given username already exists (we have `/en-US/profiles/<username>` which will 404 if the username is not already taken, but the responses are HTML pages, and that's just an ugly way to do it), so I can create one.

More tomorrow!

**Comment by escattone** [comment]
@schalkneethling Here's a summary of what I think I should do for you at the very least:

- Create a new function `is_username_taken(user)` available to Jinja
- Create a new API endpoint for doing the same

I'm not sure I understand what you need regarding an email address. Do you want something like the above but for an email address instead of a username? If that's the case, however, my understanding is that unlike usernames, email addresses do not have to be unique.

**Comment by atopal** [comment]
>       The `email_addresses` variable above would be a list of dictionaries, where that list includes both verified and unverified email addresses from GitHub, and where each dictionary represents a single email address and has the keys `email` (the actual email address as a string), `verified` (boolean, which means verified by GitHub), `primary` (boolean), and `visibility` (a string, we should only use email addresses with a visibility of `"public"`).

Sorry for butting in, just saw this and that is most likely for usage on github. When you use the github interface to fork, commit and send a pull request, it will use your full email address by default. You can set your email address to private and not have it show up in public commits.  I don't think this affects us. We should suggest their primary email address regardless of whether its set to be private or public. On MDN we make sure to keep that email address private anyway.

**Comment by escattone** [comment]
@atopal That's a great point, thanks so much for you input!

**Comment by schalkneethling** [comment]
> @schalkneethling Here's a summary of what I think I should do for you at the very least:
> 
>     * Create a new function `is_username_taken(user)` available to Jinja
> 
>     * Create a new API endpoint for doing the same
> 
> 
> I'm not sure I understand what you need regarding an email address. Do you want something like the above but for an email address instead of a username? If that's the case, however, my understanding is that unlike usernames, email addresses do not have to be unique.

Thanks so much @escattone that sounds great!

**Comment by escattone** [comment]
The work here is done. The next steps are either clear or, in the case of the email addresses, will soon be clear after @schalkneethling discovers more of what he needs. Closing this issue.
