### ISSUE TITLE
Chinese search page throws error

### ISSUE THREAD

**Issue by chxlvwh** [mozilla/kuma#5958]
when I search a keyword in search input，it will show an error page with a header 'Application rendering error' on it, and a sentence 'An unhandled error occurred in the application. We apologize for the inconvenience!' under the title

**Comment by atopal** [comment]
Hey there, can you tell what you were searching for and what browser you were using?

**Comment by chxlvwh** [comment]
Almost all content. The browser is Chrome and the version is 77.0.3865.90. Oh, I just switched languange to English, and it worked well, and Japanese as well. Only Chinese does not work. Maybe you can open this site 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for' and search on this page.

**Comment by atopal** [comment]
Thank you! Yeah, it looks like it's Chinese specifically.

**Comment by chxlvwh** [comment]
Em...by the way, how long will the problem be solved. The MDN is funny.

**Comment by peterbe** [comment]
Annoyingly the error doesn't happen locally:
<img width="1494" alt="Screen Shot 2019-10-10 at 8 36 11 AM" src="https://user-images.githubusercontent.com/26739/66569245-22bd3800-eb39-11e9-9914-380af6b45f3f.png">

Something did change today with regards to how search works. Perhaps it got fixed.

**Comment by peterbe** [comment]
> Em...by the way, how long will the problem be solved.

Assuming it's easy to figure out what's wrong, it'll take minutes. 
But it might take days to have it fully fixed, reviewed, and deployed. 

Do you want to help out? All you need is docker.

**Comment by peterbe** [comment]
@chxlvwh If it helps you can just put in `wiki.` at the start of the URL and it should work there: https://wiki.developer.mozilla.org/zh-CN/search?q=%E6%96%B9%E6%B3%95%E4%BC%9A%E6%A0%B9%E6%8D%AE%E7%BB%99%E5%AE%9A%E7%9A%84%E9%94%AE

**Comment by peterbe** [comment]
See if you can get up and running on https://kuma.readthedocs.io/en/latest/installation.html and ping if you get stuck.

**Comment by escattone** [comment]
The chain of events, starting from the root cause, was as follows:
- We do not send the locale's `pluralFunction` (used within `ngettext`) with the data that we encode into `window._react_data`. During SSR, the proper `pluralFunction` is defined and used, but it's never encoded back into what we send to the client, so the incorrect `pluralFunction` is not available during hydration on the client side (assuming it's used during hydration). For the search results page, we're not yet doing SSR (although we will later tonight after the deployment), so the React rendering occurred completely on the client side.
- When we called `ngettext` [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/search-results-page.jsx#L70), the plural function used was the default (for English), which returns an index of `1` for a count of zero or something greater than 1, but the plural form for Chinese locales is always the same as the singular, so the translation array returned from the catalog has only one item and the index of `1` returns an `undefined` object (since it's outside the bounds of the array).
- That `undefined` object then gets fed into the `interpolate` call [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/l10n.js#L142) and raises an exception [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/l10n.js#L148.)

The root cause is that we can't yet trust the `pluralFunction` that we initialize on the client side [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/index.jsx#L26), since we don't send it as part of `data` (`data.pluralFunction` is always `undefined`. This means we're always using the default plural function, which is the English one.

In #5966, I make `ngettext` safer, so it never returns an `undefined`, which I think is a nice piece to have and fixes this issue, but the root cause remains to be addressed.

**Comment by chxlvwh** [comment]
> The chain of events, starting from the root cause, was as follows:
> 
> * We do not send the locale's `pluralFunction` (used within `ngettext`) with the data that we encode into `window._react_data`. During SSR, the proper `pluralFunction` is defined and used, but it's never encoded back into what we send to the client, so the incorrect `pluralFunction` is not available during hydration on the client side (assuming it's used during hydration). For the search results page, we're not yet doing SSR (although we will later tonight after the deployment), so the React rendering occurred completely on the client side.
> * When we called `ngettext` [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/search-results-page.jsx#L70), the plural function used was the default (for English), which returns an index of `1` for a count of zero or something greater than 1, but the plural form for Chinese locales is always the same as the singular, so the translation array returned from the catalog has only one item and the index of `1` returns an `undefined` object (since it's outside the bounds of the array).
> * That `undefined` object then gets fed into the `interpolate` call [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/l10n.js#L142) and raises an exception [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/l10n.js#L148.)
> 
> The root cause is that we can't yet trust the `pluralFunction` that we initialize on the client side [here](https://github.com/mozilla/kuma/blob/a0a7d13c5a507511e6bb0b7822ca1ee3de107110/kuma/javascript/src/index.jsx#L26), since we don't send it as part of `data` (`data.pluralFunction` is always `undefined`. This means we're always using the default plural function, which is the English one.
> 
> In #5966, I make `ngettext` safer, so it never returns an `undefined`, which I think is a nice piece to have and fixes this issue, but the root cause remains to be addressed.

Looks good! But I tryed right now and it still didn't work . Is it the reason that it has not been deployed?

**Comment by escattone** [comment]
@chxlvwh It's fixed now. I hadn't yet deployed when you tried a bit earlier. Thanks again for reporting this!

**Comment by escattone** [comment]
By the way, I was able to replicate this and debug locally by checking out [this commit](https://github.com/mozilla/kuma/commit/a5631c5a33f8f4ccc1bacfa0f3050d5ff9d7f34e).

**Comment by chxlvwh** [comment]
Great! Search results pages are perfectly presented.Thank you for solving this problem so quickly.
